// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import sqs "github.com/aws/aws-sdk-go/service/sqs"

// MessageReceiveDeleter is an autogenerated mock type for the MessageReceiveDeleter type
type MessageReceiveDeleter struct {
	mock.Mock
}

// DeleteMessageBatch provides a mock function with given fields: _a0
func (_m *MessageReceiveDeleter) DeleteMessageBatch(_a0 *sqs.DeleteMessageBatchInput) (*sqs.DeleteMessageBatchOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sqs.DeleteMessageBatchOutput
	if rf, ok := ret.Get(0).(func(*sqs.DeleteMessageBatchInput) *sqs.DeleteMessageBatchOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteMessageBatchOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sqs.DeleteMessageBatchInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiveMessage provides a mock function with given fields: _a0
func (_m *MessageReceiveDeleter) ReceiveMessage(_a0 *sqs.ReceiveMessageInput) (*sqs.ReceiveMessageOutput, error) {
	ret := _m.Called(_a0)

	var r0 *sqs.ReceiveMessageOutput
	if rf, ok := ret.Get(0).(func(*sqs.ReceiveMessageInput) *sqs.ReceiveMessageOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ReceiveMessageOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sqs.ReceiveMessageInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
